name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Java setup
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.15
      - name: Gradle clean build
        run: gradle clean build -P build-backend